changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features and Capabilities
      labels:
        - enhancement
        - capability
        - agent-interface
    - title: Routing and Adapters
      labels:
        - routing
        - adapter
        - schema
    - title: Benchmark and Quality
      labels:
        - benchmark
        - area/ci
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - chore
        - dependencies
    - title: Other Changes
      labels:
        - "*"
