coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
comment:
  layout: "reach,diff,flags,files"
ignore:
  - "packages/ghx-router/src/gql/generated/**"
  - "packages/ghx-router/src/gql/operations/*.generated.ts"
  - "packages/ghx-router/scripts/**"
  - "packages/ghx-router/src/cli/**"
  - "packages/ghx-router/src/shared/**"
  - "packages/ghx-router/src/agent-interface/prompt/**"
  - "packages/ghx-router/src/agent-interface/tools/explain-tool.ts"
  - "packages/ghx-router/src/core/contracts/tasks/**"
  - "packages/ghx-router/src/core/execute/execute.ts"
  - "packages/ghx-router/src/core/execution/adapters/cli-adapter.ts"
  - "packages/ghx-router/src/core/execution/adapters/cli-capability-adapter.ts"
  - "packages/ghx-router/src/core/execution/adapters/rest-adapter.ts"
  - "packages/ghx-router/src/core/registry/index.ts"
  - "packages/ghx-router/src/core/routing/reason-codes.ts"
  - "packages/ghx-router/src/gql/client.ts"
  - "packages/benchmark/src/cli/**"
  - "packages/benchmark/src/runner/**"
  - "packages/benchmark/src/scenario/loader.ts"
  - "packages/benchmark/src/report/**"
  - "packages/benchmark/src/extract/envelope.ts"
