coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
comment:
  layout: "reach,diff,flags,files"
ignore:
  - "packages/ghx-router/src/gql/generated/**"
  - "packages/ghx-router/src/gql/operations/*.generated.ts"
